### PR TITLE
Fix addition and subtraction

### PR DESCRIPTION
**Pull request by omarandlorraine**
solid65 is throwing up some errors with add and subtract, so I've started this to fix it up a bit.

(Locally, I have a solid65 which is rigged to only do add and subtract, and does not exercise decimal mode. When I'm satisfied that this emulator agrees with the rubbermallet one, I'll mark this pull request as ready.)

### CODE REVIEW

**Comment by omarandlorraine** [comment]
There was one bug to do with carry propagation, possibly introduced by me 😱

Turns out that most of the "bugs" thrown up by solid65 here were because of decimal mode involving invalid inputs. Most emulators get this wrong, and in different ways. If this is something we want to do correctly, we need to first establish what "correct" means!

**Comment by mre** [comment]
What's the status on this? Looks good to me, but I'm not sure if you were in the middle of something before this can be merged.

**Comment by omarandlorraine** [comment]
> What's the status on this? 

I think we need a decision on what to do about decimal addition/subtraction on bytes that are not valid decimal. Mimic original hardware (and then, which one?)? Mimic other emulators (and then, which one?)?

**Comment by omarandlorraine** [comment]
> So looks like we're done here?

That's fine, in that case it's ready to merge

**Comment by mre** [comment]
Yay, great improvement. Thanks! 🙏

**Pull request merged**
