### PR TITLE
Fuzztesting

### PR DESCRIPTION
**Pull request by omarandlorraine**
This pull request pulls in the git submodule perfect6502.

Then we can start fuzztesting moz6502 and perfect6502 against eachother.

### CODE REVIEW

**Comment by omarandlorraine** [comment]
I wonder if we're not better off creating a separate repository for testing many emulators against each other, rather than testing just this one against perfect6502. What do you think?

**Comment by mre** [comment]
That's true. Surprised that there isn't already a comparison repository out there; at least I couldn't find any. I'd be in favor of creating a separate repo for that. This way we could also share the test scripts and roms. 

To begin with, we could compare
* https://github.com/gianlucag/mos6502
* perfect6502
* and ours

Are you interested in creating the comparison repo in your own namespace? Seems like the most reasonable thing to do, given that it's independent of a single implementation. 😃

**Comment by mre** [comment]
We could also move the test rom from https://github.com/mre/mos6502/pull/17 over to the new repository.

**Comment by omarandlorraine** [comment]
>Surprised that there isn't already a comparison repository out there

This surprised me as well when I was working on my fork of fake6502. It's the obvious thing to do, isn't it. The idea doesn't even turn up for other popular architectures like Z80 or Arm.

>Are you interested in creating the comparison repo in your own namespace?

Yep I'll do that. I'll add the ones you said and some others. So I'll go ahead and close this pull request.

**Comment by mre** [comment]
Once you created the repo I'd be thankful for a pull request that adds a link to it. 😃

**Pull request closed without merging**
