### PR TITLE
add option to statically disable decimal mode

### PR DESCRIPTION
**Pull request by omarandlorraine**
So I've never looked at conditional compilation before in Rust. Maybe I got something wrong here. But the tests still pass.

### CODE REVIEW

**Comment by mre** [comment]
the cfg! macro checks for the condition at runtime. Did you intend to do that? There's also a config attribute for compile-time checks (https://doc.rust-lang.org/rust-by-example/attribute/cfg.html). On a more general note, how about we put the setting behind a feature flag? This way, library users can decide to enable it if they like. The syntax is [quite similar](https://stackoverflow.com/questions/55515686/how-do-i-check-for-features-set-in-rust-during-compilation).

**Comment by omarandlorraine** [comment]
I did not intend to check that flag at runtime! Thanks for the catch. I'm learning about conditional compilation in Rust as I go here so bear with.

**Comment by omarandlorraine** [comment]
So what I believe we've got here is `#[cfg(feature="disable_decimal_mode")]` essentially checks if the host has stuck in `features = "disable_decimal_mode"` in the Cargo.toml. This way, the flag gets passed to rustc when mos6502, its dependency, gets compiled. This will chop & change what gets compiled in. I wonder if there's anything more we need to do here.

**Comment by omarandlorraine** [comment]
Okay, CI is failing but it's nothing to do with this code I've just changed. I'll take a look in the morning.

**Comment by omarandlorraine** [comment]
Here, the tests pass again. I pushed a commit to master and then rebased this branch; hope that's okay

**Comment by omarandlorraine** [comment]
Here, I think this branch is ready. What do you think?

**Comment by mre** [comment]
From my experience, features are usually phrased "permissively", so I'd change the feature name to just `decimal_mode`.
Then

```rust
#[cfg(not(feature = "disable_decimal_mode"))]
```

becomes

```rust
#[cfg(feature = "decimal_mode")]
```

At a later point in time we could consider grouping those features into more generic "emulation modes" &mdash; one for NMOS and one for CMOS for example. We could add the missing instructions for CMOS then as well. Let's keep it simple for now, though. 😉

**Comment by mre** [comment]
Oh and if we want to enable decimal mode by default, we can add it to the list of default features:
```
default = ["decimal_mode"]
```

**Comment by omarandlorraine** [comment]
Oh I see, that's better yes I agree.

But how do we put in `cargo test -F something` to disable it then? Or in a host project's Cargo.toml?

**Comment by mre** [comment]
To disable default features, you can pass 

```
cargo test --no-default-features
```

As described in https://doc.rust-lang.org/cargo/commands/cargo-test.html#feature-selection.
So in our case we'd run `cargo test` for the default version _with_ decimal support and `cargo test --no-default-features` for the vanilla version _without_ decimal support.
Does that answer your question? 🤔

**Comment by omarandlorraine** [comment]
I suppose so, but in the future we'd want something like `default = ["illegal-opcodes" "decimal-mode"]`. And then we'd want to test all default features except decimal mode.

**Comment by mre** [comment]
Ah, the common way is to first disable all default features and then re-enabling the ones under test, e.g.
```
cargo test --no-default-features -F illegal-opcodes
```

The same is done in the `Cargo.toml` of some popular projects like ripgrep [here](https://github.com/BurntSushi/ripgrep/blob/3bb71b0cb8727ac43237af78ba5c707298de0128/Cargo.toml#L65-L68).

Granted, it gets a little tedious with many features, but it's mostly a CI thing as normal users would probably just enable one feature in the end &mdash; we can combine features into more general features to make that easier if we like. 😉

If we get to a point where testing all combinations gets awkward, we can list them in a `Makefile` target, but let's wait until we get there.

**Comment by omarandlorraine** [comment]
How's this?

**Comment by mre** [comment]
Great, looks good to me. Thanks a lot @omarandlorraine.

**Pull request merged**
