### PR TITLE
Proper wrap-around for address calculations

### PR DESCRIPTION
**Pull request by omarandlorraine**

### CODE REVIEW

**Comment by omarandlorraine** [comment]
the tests do not compile (yet) because I have changed some types here and there.

**Comment by omarandlorraine** [comment]
Do we know what exactly the types `Address` and `AddressDiff` are meant to accomplish? I've moved to just using native datatypes here for ergonomy.

**Comment by omarandlorraine** [comment]
I think just some unit tests and this is ready

**Comment by mre** [comment]
> Ah, I see now that using u16 instead of Address is a breaking change. Is this acceptable?

That's fine.

**Comment by omarandlorraine** [comment]
Okay, i think this is ready now

**Pull request merged**
