### PR TITLE
Implementation of RTS

### PR DESCRIPTION
**Pull request by omarandlorraine**
We need to implement RTS (I also happened to spot RTI is missing; this pull request will probably also implement that).

So far, it's just a basic, untested implementation. As with the other instructions, there is also no attempt at cycle-accuracy.

### CODE REVIEW

**Comment by omarandlorraine** [comment]
I found that the `pull_from_stack` logic is b0rked as well.

It has to do with how the CPU post-decrements the stack pointer when pushing, and post-increments the stack when pulling. That means it always has to discard one byte when pulling (the stack pointer will be pointing to the next vacant stack location before the pull).

According to solid65, this affects `plp` and `pla` opcodes also.

**Comment by omarandlorraine** [comment]
> there is also no attempt at cycle-accuracy.

Is this something we're going for here, or?

**Comment by mre** [comment]
Thanks for the update. I appreciate that look into it. ⭐ 

About cycle accuracy, yes, it would be nice to add that at some point.
Do you have an idea on how to go about this? The way I see it, we'd have to add the number of cycles for each instruction and then add the correct number of `tick`s or `NOOP`s before executing the next instruction. Is that correct?

**Comment by omarandlorraine** [comment]
>The way I see it, we'd have to add the number of cycles for each instruction and then add the correct number of ticks or NOOPs before executing the next instruction. 

Yes, but there's more to it.

If you have a look at [this document](http://www.atarihq.com/danb/files/64doc.txt), its description of the RTS instruction (a little less than half-way down the document) shows what we have to do:

1. Read the opcode
2. Read the next opcode (and ignore this byte)
3. Pop a dummy byte off the stack (just to update the stack pointer before the "real" pops in steps 4 and 5)
4. Pop the low byte of the program counter
5. Pop the high byte of the program counter
6. Read the byte just before the instruction we're going to resume from (just to update the program counter)

The reason for step 6 is that JSR starts pushing the PC before it's finished executing, so the program counter on the stack still points to the last byte of the JSR, so RTS needs to increment it again so the instruction after the JSR will be read next.

JSR is a simple example, some of the conditional branches, and indexed addressing modes can get kinda involved.

I think it may take major architectural changes before we will be able to make serious attempt at cycle-accuracy for all opcodes, but we can at least do the simple ones easily enough!

**Comment by mre** [comment]
Thanks for the thorough explanation. Yeah, let's keep cycle accuracy as a stretch-goal for the future.
Looking at your description of the RTS instruction, I can now understand why it takes so many cycles.

**Comment by omarandlorraine** [comment]
JSR is also unimplemented

**Comment by omarandlorraine** [comment]
Okay. Other than:
1. differences in cycle count
2. errors in ADC and SBC (carry flag and decimal logic is sometimes wrong but I think this needs another PR)
3. handling of unknown opcodes

that seems to be all the differences solid65 has found between the rubbermallet emulator and solid65. So from my end this is ready to merge.

**Review by mre — APPROVED** [review]

**Pull request merged**
