### PR TITLE
Tarvis integration

### PR DESCRIPTION
**Pull request by senden9**
See issue  #2. Add CI integration.
See that [example report](https://travis-ci.org/senden9/mos6502/builds/446154284) here. I configured nightly as allowed failure because it can be happen that a build fail because a compiler bug.

Later when you set up the Tarvis account for I would suggest to add a CI Status Image. This let your project look better maintained. If you grand me the permissions I can also setup Tarvis for you. But I am not sure if this is possible because this repo in in your private namespace rather than in the namespace of an organization.

### CODE REVIEW

**Comment by mre** [comment]
Thanks @senden9 👍

**Comment by mre** [comment]
Just set up a travis account. Building right now...

**Comment by mre** [comment]
https://travis-ci.org/mre/mos6502/builds/446161365

**Comment by mre** [comment]
Added a badge to the `README.md` now. Thanks for your contribution. 🌞

**Comment by senden9** [comment]
I did not setup an build cache because various sources and my own measurement shows that this is slower than a simple rebuild in the case of rust + tarvis.

**Comment by senden9** [comment]
Thanks for maintaining that project :D

**Pull request merged**
