### PR TITLE
Add CI pipeline

### PR DESCRIPTION
**Pull request by mre**
Related to #70.

### CODE REVIEW

**Comment by omarandlorraine** [comment]
I wonder if we could rig it to check for yanked versions, for bitflags and whatever else.

I see this warning

```
 warning: package `bitflags v2.2.0` in Cargo.lock is yanked in registry `crates-io`, consider updating to a version that is not yanked
```

**Comment by mre** [comment]
Yes.

https://blog.rust-lang.org/inside-rust/2020/01/23/Introducing-cargo-audit-fix-and-more.html

```
cargo audit --deny-warnings
```

I can add that. Good idea.

**Comment by omarandlorraine** [comment]
Good job! But then I suppose we need to downgrade bitflags again.

(Actually, what even *is* going on with bitflags at the moment?! Seems like there some update every other day! We're not using half their features either. So we could easily get rid of it and roll our own couple of functions for getting a handful of flags in and out of a u8.)

**Comment by mre** [comment]
Yeah, good point. No clue what's up there. I haven't followed the crate too actively lately, to be honest. I downgraded to 2.1.0

**Pull request merged**
