### PR TITLE
Carry bug

### PR DESCRIPTION
**Pull request by omarandlorraine**
Here is a commit that demonstrates the bug by adding a failing test.

### CODE REVIEW

**Comment by omarandlorraine** [comment]
The bug's locus is the two wrapping_adds on line 530 of cpu.rs

**Comment by mre** [comment]
So that means if we remove the second wrapping_add, it should work right? Can you update your PR with the fix? I wonder if all the other unit tests will pass.

**Comment by omarandlorraine** [comment]
We need both wrapping_adds, but we also need to set the carry flag if b=0xFF and carry_before = true.

I'll try and code up a solution in the coming days

**Comment by mre** [comment]
Thanks a lot for looking into this. 👍

**Comment by mre** [comment]
Merged. 🥳 
Thanks for your contribution. If you like to become a co-maintainer of this repo, please send me a mail. I'd love to have you on board.

**Comment by omarandlorraine** [comment]
>If you like to become a co-maintainer of this repo, please send me a mail. I'd love to have you on board.
Message sent 👍

**Pull request merged**
